language: android

android:
  components:
    - build-tools-21.1.1
    - android-21
    - extra

before_install:
    - chmod +x ./run-build.sh
    - chmod +x ./gradlew

after_success:
    - git config --global user.email "sumimaito@hotmail.com"
    - git config --global user.name "SumiMakito"
    - export GITHUB_TAG=Snapshot_${TRAVIS_BRANCH}_Build.${TRAVIS_BUILD_NUMBER}
    - git tag ${GITHUB_TAG}
    - git push --quiet https://${GITHUB_KEY}@github.com/SumiMakito/QuickKV.git ${GITHUB_TAG}

deploy:
    provider: releases
    api_key:
      secure: LdXNHVLhA2XoGRplJY7B/+jX4san2BvE1kNpQNSSflANL/IKF+8gFv9TDV6CJyFfSSpNmprnBfqYvsZBwuxDsWQ14WJcGROWfBXPgCuPYh+48cRxfyuMfTjmAnYaupe9KqME/VhnSyn8kstw0/7zbYQALehdpjIRvuV5l5OuC5K38WJibzHsC+TRTe6+nbkXxfz1cXdPq8SZhddhL9wYQppDG2TG72mZ7zpIW6Ein5o+rQ5w5+WfOuMVf+42pbUjSu4ha+QwGZF9eWSQGQwUcgBvmtx/V5v2yJJCJbs9+HlmQ+j4JFZTuG3uekkW23AVEvYW6OJ4Hy8E7sGk2xUKm71DlfLG82GcLEKGiK43aa4Y4A00NrH+em+6F24RH6PERXQtRzBV9v3x2RQqdTkCl52AMceL0p1fR56aYQQARitJuiLcUkCtGI3yRTZEOJcjAZr1NZgqOWcOmda97pNG6U41wDrsDKnykV91aFhUO7llTE1OzhtXHqptOxazl+jy8BRckJE8cnj1LKsHWSfU5Z82IMSgdWwQuxzSVKlE3B2Y0Z7xtoHcd1cxRvNlmICjNgyQpyHqPI4BEIFd/flBe2MunkN2ka0kJU0B4qfskBHxq5qGtDDTb3of/wd9y1GHFOSp7d3/vCq62vEkJdO1Joe5JqVixUg9p3mSQJ+uHMc=
    file:
      - library/build/libs/QuickKV_${GITHUB_TAG}_source.jar
      - library/build/libs/QuickKV_${GITHUB_TAG}_javadoc.jar
    skip_cleanup: true
    on:
      repo: SumiMakito/QuickKV
      tags: false

script:
    ./run-build.sh
